### ISSUE TITLE
find parent function in single kernel LBVH compares incorrectly.

### ISSUE THREAD

**Issue by natevm** [Niravaana/HIP-BVH-Construction#1]
I was looking through your single kernel LBVH code, and noticed that you are comparing δ(j-1,j) with itself. I think this might be a typo, shouldn’t this be between δ(I-1,i) and δ(j,j+1)?

https://github.com/Niravaana/HIP-BVH-Construction/blob/7a74fb984bd493cea1eb0702036fd6417999edd1/src/SinglePassLbvhKernel.h#L53

**Comment by Niravaana** [comment]
Hey Nathan

I cannot thank you enough!
It should be between j-1, j and i-1, i
findHighestDiffBit(mortonCodes, j - 1, j, n) <
findHighestDiffBit(mortonCodes, i - 1, i, n)

And because of this somehow the BVH was correct though the performance was
super bad, and I was banging my head going through ISA lol

![image](https://github.com/user-attachments/assets/1864d6ce-5218-4cba-bc58-2c5b4b7a04d4)

you see I suspect mostly it was doing the same comparison for finding
parent and loading global data again and again causing it to be super slow
lol.

Again thanks a lot, I can sleep now.
I have pushed a fix. Cheers.

Wishing you best!
Paritosh
